### ISSUE TITLE
Default brightness too low?

### ISSUE THREAD

**Issue by kilrah** [amalmin/SCTVcode#4]
For discussion...

Since the PWM brightness was introduced the clock is barely visible in a daylit room without cranking the hardware intensity control to the point where the beam loses focus. IMO the default of 60 is too low, should probably be seen the opposite way, instead of starting at 60 by default and making some things brighter but sometimes nothing is 100, have everything at 100 by default and reduce what needs to be different.

**Comment by amalmin** [comment]
Yes, it is not ideal.  I loaded the original FW last night to compare and the new code is a bit dimmer than I expected (it had been quite a while since i had seen the original FW).  On my unit it isn't a huge difference, but it is definitely dimmer.  

The original idea was to reserve some brightness for really bright objects (sort of like the over-driven objects in the original vector Asteroids game).  With the 'normal' brightness point set to be about as bright as that of the original FW.  

Simply setting BRIGHTNESS_DEFAULT to 100 works pretty well, but looses the ability to make things like clock hands brighter than the rest of the clock.  Maybe what should happen is the addition of 'double scan' to the end of the brightness scale?  0-100 could be PWM, 120 or 150 or something could mean double and triple scan?  Those levels would incur the performance drop for the multiple scans, but it would allow a wider dynamic range and let DEFAULT sit at 100.  This would still have the advantage of not requiring the face drawing code to know anything about multiple-scanning.

Not sure of it should be 'beyond the scale' like 120 or 150, or part of the scale with triple-scan at 100 and DEFAULT at 80 or something.

**Comment by amalmin** [comment]
Okay.  I've moved BRIGHTNESS_DEFAULT to 100.  Brightness values >100 will result in drawing the object one additional time for each increment beyond 100.  There is a performance impact when going beyond 100 (same as in the original code) but there doesn't seem to be any impact from the infrastructure used to allow this.

**Comment by kilrah** [comment]
Yeah looks good!

> Simply setting BRIGHTNESS_DEFAULT to 100 works pretty well, but looses the ability to make things like clock hands brighter than the rest of the clock.

I mean if you set the hands at 100/default and the rest at 80 then the hands are brighter than the rest of the clock... but yeah it's nice to have the multiple pass option since that's the only thing that does give more dynamic range, IMO on the Expo brightness scale with the hardware control at the max sharp setting the only reasonably usable ones are 60-100, _maybe_ 50 but below it's just being eclipsed by the brighter parts.

**Comment by amalmin** [comment]
Interesting.  On mine I can see all dots on the Exp line except for the 10% one.

**Comment by kilrah** [comment]
I can too, I meant that if there's something significant that's at 100% like the hands then something at 40 is barely visible due to being "blinded" by the bright stuff.
